[Open AI]
AZURE_OPENAI_ENDPOINT = "https://az-openai-services.openai.azure.com/"
AZURE_OPENAI_API_KEY = "7e0c34234249438cbd2eab66e75dc0e5"
AZURE_OPENAI_DEPLOYMENT_NAME = "depl-gpt4o"
AZURE_OPENAI_API_VERSION = "2025-01-01-preview"
